---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extension-metrics-api-controller
  namespace: default
  labels:
    api: extension-metrics-api
    controller: "true"
spec:
  selector:
    matchLabels:
      api: extension-metrics-api
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: extension-metrics-api
        controller: "true"
    spec:
      containers:
      - name: controller
        image: haoranleonard/test-aws:extension-metrics-v0.1
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: extension-metrics-api
